### ISSUE TITLE
Possibility of attribute info for items in InternalNameMappings.json

### ISSUE THREAD

**Issue by DarthGigi** [kr45732/skyblock-plus-data#4]
I was wondering if it's possible to add attribute information such as if the item is auctionable, tradable, sellable, etc to the items in the json list?
![Wiki](https://github.com/kr45732/skyblock-plus-data/assets/47110839/2941f980-898a-49dd-a583-c5d2320e49b8)

**Comment by kr45732** [comment]
This will not be possible. Since the list is generated via the [NEU repo](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/blob/master/items/HYPERION.json), I don't have a way to get that information since they do not track it.
